# 영화진흥위원회 데이터 수집

## setting

In [79]:
import requests

class URLMaker:
    """
    영화진흥위원회 API URL 생성 클래스
    """
    
    url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest'

    def __init__(self, key):
        """
        API key 초기화
        """
        self.key = key

    def daily_boxoffice_url(self, targetDt, itemPerPage=10, multiMovieYn='', repNationCd='', wideAreaCd=''):
        """
        일별 박스오피스 URL 생성
        """
        return f'{self.url}/boxoffice/searchDailyBoxOfficeList.json?key={self.key}&targetDt={targetDt}&itemPerPage={itemPerPage}&multiMovieYn={multiMovieYn}&repNationCd={repNationCd}&wideAreaCd={wideAreaCd}'

    def weekly_boxoffice_url(self, targetDt, weekGb='0', itemPerPage=10, multiMovieYn='', repNationCd='', wideAreaCd=''):
        """
        주간/주말 박스오피스 URL 생성
        weekGb: 0(주간), 1(주말), 2(주중)
        """
        return f'{self.url}/boxoffice/searchWeeklyBoxOfficeList.json?key={self.key}&targetDt={targetDt}&weekGb={weekGb}&itemPerPage={itemPerPage}&multiMovieYn={multiMovieYn}&repNationCd={repNationCd}&wideAreaCd={wideAreaCd}'

    def movie_list_url(self, curPage=1, itemPerPage=10, movieNm='', directorNm='', openStartDt='', openEndDt='', 
                      prdtStartYear='', prdtEndYear='', repNationCd='', movieTypeCd=''):
        """
        영화목록 URL 생성
        """
        return f'{self.url}/movie/searchMovieList.json?key={self.key}&curPage={curPage}&itemPerPage={itemPerPage}&movieNm={movieNm}&directorNm={directorNm}&openStartDt={openStartDt}&openEndDt={openEndDt}&prdtStartYear={prdtStartYear}&prdtEndYear={prdtEndYear}&repNationCd={repNationCd}&movieTypeCd={movieTypeCd}'

    def movie_info_url(self, movieCd):
        """
        영화 상세정보 URL 생성
        """
        return f'{self.url}/movie/searchMovieInfo.json?key={self.key}&movieCd={movieCd}'

    def people_list_url(self, curPage=1, itemPerPage=10, peopleNm='', filmoNames=''):
        """
        영화인목록 URL 생성
        """
        return f'{self.url}/people/searchPeopleList.json?key={self.key}&curPage={curPage}&itemPerPage={itemPerPage}&peopleNm={peopleNm}&filmoNames={filmoNames}'

    def people_info_url(self, peopleCd):
        """
        영화인 상세정보 URL 생성
        """
        return f'{self.url}/people/searchPeopleInfo.json?key={self.key}&peopleCd={peopleCd}'


    

In [80]:
MY_API_KEY = 'd56ce424e919ff32ac17d74f244ea605'
url_maker = URLMaker(MY_API_KEY)

In [81]:
url_maker.key

'd56ce424e919ff32ac17d74f244ea605'

In [82]:
daily_url = url_maker.daily_boxoffice_url('20250201')
print(daily_url)

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=d56ce424e919ff32ac17d74f244ea605&targetDt=20250201&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=


In [83]:
weekly_url = url_maker.weekly_boxoffice_url('20250201')
print(weekly_url)

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key=d56ce424e919ff32ac17d74f244ea605&targetDt=20250201&weekGb=0&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=


In [84]:
info_url = url_maker.movie_info_url('19950084')
print(info_url)

http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=d56ce424e919ff32ac17d74f244ea605&movieCd=19950084


## 영화 상세정보 조회

- **영화 상세정보 api**를 사용합니다.
- 영화 코드(movieCd)를 입력받아 해당 영화의 상세 정보를 조회합니다.
- 다음 정보를 순서대로 출력합니다:
    - 영화 제목 (제작연도)
    - 감독 (첫 번째 감독)
    - 주연 배우 (첫 번째, 두 번째 배우)
    - 장르 (첫 번째 장르)

In [85]:
info_url = url_maker.movie_info_url('19950084')
print(info_url)

http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=d56ce424e919ff32ac17d74f244ea605&movieCd=19950084


In [86]:
movie_info = requests.get(info_url)
movie_detail = movie_info.json()
print(movie_detail)

{'movieInfoResult': {'movieInfo': {'movieCd': '19950084', 'movieNm': '쇼생크 탈출', 'movieNmEn': 'The Showshank Redemption', 'movieNmOg': '', 'showTm': '142', 'prdtYear': '1994', 'openDt': '19950204', 'prdtStatNm': '개봉', 'typeNm': '장편', 'nations': [{'nationNm': '미국'}], 'genres': [{'genreNm': '드라마'}], 'directors': [{'peopleNm': '프랭크 다라본트', 'peopleNmEn': 'Frank Darabont'}], 'actors': [{'peopleNm': '팀 로빈스', 'peopleNmEn': 'Tim Robbins', 'cast': '', 'castEn': ''}, {'peopleNm': '모건 프리먼', 'peopleNmEn': 'Morgan Freeman', 'cast': '', 'castEn': ''}], 'showTypes': [{'showTypeGroupNm': '필름', 'showTypeNm': '필름'}, {'showTypeGroupNm': '2D', 'showTypeNm': '디지털'}], 'companys': [{'companyCd': '20102502', 'companyNm': '캐슬 락 엔터테인먼트', 'companyNmEn': 'Castle Rock Entertainment', 'companyPartNm': '제작사'}, {'companyCd': '20102771', 'companyNm': '콜럼비아 픽쳐스 코포레이션', 'companyNmEn': 'Columbia Pictures Corporation', 'companyPartNm': '제작사'}, {'companyCd': '20122837', 'companyNm': '(주)팝엔터테인먼트', 'companyNmEn': 'Pop Entertain

In [87]:
print(movie_detail['movieInfoResult']['movieInfo']['movieNm'])

쇼생크 탈출


In [88]:
print(movie_detail['movieInfoResult']['movieInfo']['prdtYear'])

1994


In [89]:
print(movie_detail['movieInfoResult']['movieInfo']['directors'][0]['peopleNm'])

프랭크 다라본트


In [90]:
print(movie_detail['movieInfoResult']['movieInfo']['actors'][0]['peopleNm'], ', ', movie_detail['movieInfoResult']['movieInfo']['actors'][1]['peopleNm'])

팀 로빈스 ,  모건 프리먼


In [91]:
print(movie_detail['movieInfoResult']['movieInfo']['genres'][0]['genreNm'])

드라마


In [92]:
def get_movie_detail(movie_cd):
   
    
    info_url = url_maker.movie_info_url(movie_cd)
    movie_info = requests.get(info_url)
    movie_detail = movie_info.json()
    movieinfo = movie_detail['movieInfoResult']['movieInfo']

    print(f'{movieinfo['movieNm']} ({movieinfo['prdtYear']})')
    print(f'감독: {movieinfo['directors'][0]['peopleNm']}')
    print(f'주연: {movieinfo['actors'][0]['peopleNm']}, {movieinfo['actors'][1]['peopleNm']}')
    print(f'장르: {movieinfo['genres'][0]['genreNm']}')

In [93]:
def get_movie_detail(movie_cd):
   
    
    info_url = url_maker.movie_info_url(movie_cd)
    movie_info = requests.get(info_url)
    movie_detail = movie_info.json()
    movieinfo = movie_detail['movieInfoResult']['movieInfo']

    print(movieinfo)

In [127]:
get_movie_detail('20241110')

{'movieCd': '20241110', 'movieNm': '아이유 콘서트 : 더 위닝', 'movieNmEn': 'IU CONCERT : THE WINNING', 'movieNmOg': '', 'showTm': '123', 'prdtYear': '2024', 'openDt': '20250124', 'prdtStatNm': '개봉', 'typeNm': '장편', 'nations': [{'nationNm': '한국'}], 'genres': [{'genreNm': '공연'}], 'directors': [{'peopleNm': '이예지', 'peopleNmEn': ''}, {'peopleNm': '오윤동', 'peopleNmEn': 'Yoon-Dong OH'}], 'actors': [{'peopleNm': '이지은', 'peopleNmEn': 'IU', 'cast': '', 'castEn': ''}], 'showTypes': [{'showTypeGroupNm': '2D', 'showTypeNm': '디지털'}, {'showTypeGroupNm': '4D', 'showTypeNm': '4D'}, {'showTypeGroupNm': 'IMAX', 'showTypeNm': 'IMAX'}, {'showTypeGroupNm': 'ScreenX', 'showTypeNm': 'ScreenX'}], 'companys': [{'companyCd': '20203082', 'companyNm': '씨제이포디플렉스 주식회사', 'companyNmEn': 'CJ 4DPLEX', 'companyPartNm': '제작사'}, {'companyCd': '20242041', 'companyNm': '스크린엑스 스튜디오', 'companyNmEn': 'ScreenX Studio', 'companyPartNm': '제작사'}, {'companyCd': '20204721', 'companyNm': '씨지브이 아이스콘', 'companyNmEn': 'CGV ICECON', 'companyPartNm

**출력 예시**
```
쇼생크 탈출 (1994)
감독: 프랭크 다라본트
주연: 팀 로빈스, 모건 프리먼
장르: 드라마
```

## 일별 박스오피스 조회

- **일별 박스오피스 api**를 사용합니다.
- 입력받은 날짜(YYYYMMDD 형식)의 박스오피스 정보를 조회합니다.
- 각 영화의 순위, 영화제목, 해당 일의 관객수를 출력합니다.

In [95]:
daily_url = url_maker.daily_boxoffice_url('20250201')
print(daily_url)

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=d56ce424e919ff32ac17d74f244ea605&targetDt=20250201&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=


In [96]:
movie_daily = requests.get(daily_url)
daily = movie_daily.json()
print(daily)

{'boxOfficeResult': {'boxofficeType': '일별 박스오피스', 'showRange': '20250201~20250201', 'dailyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '1663433100', 'salesShare': '39.5', 'salesInten': '525167660', 'salesChange': '46.1', 'salesAcc': '17240257840', 'audiCnt': '177129', 'audiInten': '40686', 'audiChange': '29.8', 'audiAcc': '1831557', 'scrnCnt': '1495', 'showCnt': '6165'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20247450', 'movieNm': '검은 수녀들', 'openDt': '2025-01-24', 'salesAmt': '934872220', 'salesShare': '22.2', 'salesInten': '247202440', 'salesChange': '35.9', 'salesAcc': '13206216740', 'audiCnt': '96043', 'audiInten': '14734', 'audiChange': '18.1', 'audiAcc': '1363840', 'scrnCnt': '1192', 'showCnt': '4387'}, {'rnum': '3', 'rank': '3', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20223819', 'movieNm': '말할 수 없는 비밀', 'ope

In [97]:
print(daily['boxOfficeResult']['dailyBoxOfficeList'][0]['movieNm'])

히트맨2


In [98]:
def get_daily_boxoffice(target_date):
    daily_url = url_maker.daily_boxoffice_url(target_date)
    movie_daily = requests.get(daily_url)
    daily = movie_daily.json()
    md = daily['boxOfficeResult']['dailyBoxOfficeList']

    print(f'{target_date} 박스오피스 TOP 10')
    for i in range(10):
        print(f'{i+1}위: {md[i]['movieNm']} ({md[i]['audiCnt']}명)')
        

In [99]:
get_daily_boxoffice("20250201")  # YYYYMMDD 형식으로 날짜 입력

20250201 박스오피스 TOP 10
1위: 히트맨2 (177129명)
2위: 검은 수녀들 (96043명)
3위: 말할 수 없는 비밀 (63000명)
4위: 하얼빈 (23298명)
5위: 서브스턴스 (15031명)
6위: 극장판 포켓몬스터 AG: 뮤와 파동의 용사 루카리오 (12342명)
7위: 뽀로로 극장판 바닷속 대모험 (5903명)
8위: 바다 탐험대 옥토넛 어보브 앤 비욘드 : 극지방 대작전 (4570명)
9위: 극장판 짱구는 못말려: 우리들의 공룡일기 (3801명)
10위: 아이유 콘서트 : 더 위닝 (3156명)


**출력예시**
```
20250201 박스오피스 TOP 10
1위: 히트맨2 (177129명)
2위: 검은 수녀들 (96043명)
3위: 말할 수 없는 비밀 (63000명)
4위: 하얼빈 (23298명)
5위: 서브스턴스 (15031명)
6위: 극장판 포켓몬스터 AG: 뮤와 파동의 용사 루카리오 (12342명)
7위: 뽀로로 극장판 바닷속 대모험 (5903명)
8위: 바다 탐험대 옥토넛 어보브 앤 비욘드 : 극지방 대작전 (4570명)
9위: 극장판 짱구는 못말려: 우리들의 공룡일기 (3801명)
10위: 아이유 콘서트 : 더 위닝 (3156명)
```

## 한국 영화 일별 박스오피스 조회

- **일별 박스오피스 api**를 사용합니다.
- 입력받은 날짜(YYYYMMDD 형식)의 한국 영화 박스오피스 정보를 조회합니다.
- 한국 영화만 조회하기 위해 repNationCd='K' 파라미터를 사용합니다.
- 영화가 개봉한 순서대로 정렬하여 제목, 날짜, 순위를 출력합니다.


In [100]:
kdaily_url = url_maker.daily_boxoffice_url('20250201',repNationCd='K')
kmovie_daily = requests.get(kdaily_url)
kdaily = kmovie_daily.json()
print(kdaily)

{'boxOfficeResult': {'boxofficeType': '일별 박스오피스', 'showRange': '20250201~20250201', 'dailyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '1663433100', 'salesShare': '46.0', 'salesInten': '525167660', 'salesChange': '46.1', 'salesAcc': '17240257840', 'audiCnt': '177129', 'audiInten': '40686', 'audiChange': '29.8', 'audiAcc': '1831557', 'scrnCnt': '1495', 'showCnt': '6165'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20247450', 'movieNm': '검은 수녀들', 'openDt': '2025-01-24', 'salesAmt': '934872220', 'salesShare': '25.8', 'salesInten': '247202440', 'salesChange': '35.9', 'salesAcc': '13206216740', 'audiCnt': '96043', 'audiInten': '14734', 'audiChange': '18.1', 'audiAcc': '1363840', 'scrnCnt': '1192', 'showCnt': '4387'}, {'rnum': '3', 'rank': '3', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20223819', 'movieNm': '말할 수 없는 비밀', 'ope

In [101]:
print(kdaily['boxOfficeResult']['dailyBoxOfficeList'][0])
print(kdaily['boxOfficeResult']['dailyBoxOfficeList'][1]['openDt'])

print(kdaily['boxOfficeResult']['dailyBoxOfficeList'][0]['openDt'] > kdaily['boxOfficeResult']['dailyBoxOfficeList'][1]['openDt'])

{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '1663433100', 'salesShare': '46.0', 'salesInten': '525167660', 'salesChange': '46.1', 'salesAcc': '17240257840', 'audiCnt': '177129', 'audiInten': '40686', 'audiChange': '29.8', 'audiAcc': '1831557', 'scrnCnt': '1495', 'showCnt': '6165'}
2025-01-24
False


In [102]:
temp = []

for i in range(10):
    temp.append(kdaily['boxOfficeResult']['dailyBoxOfficeList'][i]['openDt'])

temp.sort()
print(temp)

[' ', '2011-07-28', '2024-12-04', '2024-12-24', '2025-01-01', '2025-01-22', '2025-01-24', '2025-01-24', '2025-01-24', '2025-01-27']


In [103]:
kdaily_url = url_maker.daily_boxoffice_url('20250201',repNationCd='K')
kmovie_daily = requests.get(kdaily_url)
kdaily = kmovie_daily.json()
kd = kdaily['boxOfficeResult']['dailyBoxOfficeList']

kd[0].get('movieNm')

'히트맨2'

In [104]:
def get_movie_details(target_date):
    kdaily_url = url_maker.daily_boxoffice_url('20250201',repNationCd='K')
    kmovie_daily = requests.get(kdaily_url)
    kdaily = kmovie_daily.json()
    kd = kdaily['boxOfficeResult']['dailyBoxOfficeList']
    
    temp = []

    for i in range(10):
        temp.append(kd[i]['openDt'])
    # temp.sort()

    temp2 = []
    for j in range(10):
        temp2.append(kd[j]['movieNm'])

    dict_list= dict(zip(temp,temp2))
    d = sorted(dict_list.items())

    for k in range(10):
        print(f'{d[k][1]}')

    
        


                

In [105]:
def get_movie_details(target_date):
    kdaily_url = url_maker.daily_boxoffice_url('20250201',repNationCd='K')
    kmovie_daily = requests.get(kdaily_url)
    kdaily = kmovie_daily.json()
    kd = kdaily['boxOfficeResult']['dailyBoxOfficeList']
    
    for i in range(len(kd) - 1,0,-1):
        for j in range(i):
            if kd[j]['openDt'] > kd[j+1]['openDt']:
                kd[j], kd[j+1] = kd[j+1], kd[j]
            elif kd[j]['openDt'] == kd[j+1]['openDt']:
                kd[j], kd[j+1] = kd[j], kd[j+1]

    print(f'{target_date} 한국 영화 박스오피스 (개봉일 순)')
    for j in range(10):
        print(f'{kd[j]['movieNm']} ({kd[j]['openDt']}) - {kd[j]['rank']}위')

In [106]:
get_movie_details("20250201")  # YYYYMMDD 형식으로 날짜 입력

20250201 한국 영화 박스오피스 (개봉일 순)
뜻밖의 순간 : 언익스펙티드 저니 ( ) - 10위
마당을 나온 암탉 (2011-07-28) - 9위
소방관 (2024-12-04) - 8위
하얼빈 (2024-12-24) - 4위
뽀로로 극장판 바닷속 대모험 (2025-01-01) - 5위
히트맨2 (2025-01-22) - 1위
검은 수녀들 (2025-01-24) - 2위
아이유 콘서트 : 더 위닝 (2025-01-24) - 6위
귀신경찰 (2025-01-24) - 7위
말할 수 없는 비밀 (2025-01-27) - 3위


**출력예시**
```
20250201 한국 영화 박스오피스 (개봉일 순)
뜻밖의 순간 : 언익스펙티드 저니 ( ) - 10위
마당을 나온 암탉 (2011-07-28) - 9위
소방관 (2024-12-04) - 8위
하얼빈 (2024-12-24) - 4위
뽀로로 극장판 바닷속 대모험 (2025-01-01) - 5위
히트맨2 (2025-01-22) - 1위
검은 수녀들 (2025-01-24) - 2위
아이유 콘서트 : 더 위닝 (2025-01-24) - 6위
귀신경찰 (2025-01-24) - 7위
말할 수 없는 비밀 (2025-01-27) - 3위
```

## 1월 전체 주간 박스오피스 데이터 수집

- **주간/주말 박스오피스 api**를 사용합니다.
- 2025년 1월의 모든 주간(1/5, 1/12, 1/19, 1/26) 데이터를 수집합니다.
- 각 영화의 정보는 다음을 포함해야 합니다:
    - 영화제목, 개봉일, 누적관객수, 누적매출액
- 동일한 영화가 여러 주에 걸쳐 나타날 경우, 가장 최근의 정보만 저장합니다.


In [8]:
weekly_url = url_maker.weekly_boxoffice_url('20250126')
movie_weekly = requests.get(weekly_url)
weekly = movie_weekly.json()
w = weekly['boxOfficeResult']['weeklyBoxOfficeList']
print(w)

[{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'NEW', 'movieCd': '20247450', 'movieNm': '검은 수녀들', 'openDt': '2025-01-24', 'salesAmt': '5870106460', 'salesShare': '33.3', 'salesInten': '5870106460', 'salesChange': '100.0', 'salesAcc': '5870106460', 'audiCnt': '606145', 'audiInten': '606145', 'audiChange': '100.0', 'audiAcc': '606145', 'scrnCnt': '1662', 'showCnt': '21820'}, {'rnum': '2', 'rank': '2', 'rankInten': '25', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '5656681120', 'salesShare': '32.1', 'salesInten': '5628592120', 'salesChange': '20038.4', 'salesAcc': '5686993120', 'audiCnt': '601507', 'audiInten': '598386', 'audiChange': '19172.9', 'audiAcc': '604875', 'scrnCnt': '1410', 'showCnt': '24372'}, {'rnum': '3', 'rank': '3', 'rankInten': '-2', 'rankOldAndNew': 'OLD', 'movieCd': '20228796', 'movieNm': '하얼빈', 'openDt': '2024-12-24', 'salesAmt': '1401488630', 'salesShare': '8.0', 'salesInten': '-1627247790', 'sa

In [6]:
weekly_url = url_maker.weekly_boxoffice_url('20250105')
movie_weekly = requests.get(weekly_url)
weekly = movie_weekly.json()
w = weekly['boxOfficeResult']['weeklyBoxOfficeList']

print(w[0]['movieNm'])
print(w[0]['openDt'])
print(w[0]['audiAcc'])
print(w[0]['salesAcc'])

하얼빈
2024-12-24
3672922
35098771850


In [12]:
def get_weekly_boxoffice():
    dic = {}

    date = ['20250105', '20250112', '20250119', '20250126']
    
    for j in date:
        weekly_url = url_maker.weekly_boxoffice_url(j)
        movie_weekly = requests.get(weekly_url)
        weekly = movie_weekly.json()
        w = weekly['boxOfficeResult']['weeklyBoxOfficeList']
    
        for i in range(len(w)):
            title = w[i]['movieNm']
            opend = w[i]['openDt']
            audi = w[i]['audiAcc']
            sale = w[i]['salesAcc']

            dic[title] = {f'영화제목: {title}, 개봉일: {opend}, 누적관객: {audi}, 누적매출: {sale}'}

    print(dic)
    
    

In [10]:
get_weekly_boxoffice()

{'하얼빈': {'영화제목: 하얼빈, 개봉일: 2024-12-24, 누적관객: 4642215, 누적매출: 44407362460'}, '소방관': {'영화제목: 소방관, 개봉일: 2024-12-04, 누적관객: 3840551, 누적매출: 36145572270'}, '보고타: 마지막 기회의 땅': {'영화제목: 보고타: 마지막 기회의 땅, 개봉일: 2024-12-31, 누적관객: 396287, 누적매출: 3669720540'}, '수퍼 소닉3': {'영화제목: 수퍼 소닉3, 개봉일: 2025-01-01, 누적관객: 322100, 누적매출: 2950620910'}, '뽀로로 극장판 바닷속 대모험': {'영화제목: 뽀로로 극장판 바닷속 대모험, 개봉일: 2025-01-01, 누적관객: 349597, 누적매출: 2996015770'}, '무파사: 라이온 킹': {'영화제목: 무파사: 라이온 킹, 개봉일: 2024-12-18, 누적관객: 833832, 누적매출: 8188072950'}, '모아나 2': {'영화제목: 모아나 2, 개봉일: 2024-11-27, 누적관객: 3522517, 누적매출: 32533317750'}, '극장판 짱구는 못말려: 우리들의 공룡일기': {'영화제목: 극장판 짱구는 못말려: 우리들의 공룡일기, 개봉일: 2024-12-18, 누적관객: 762895, 누적매출: 7177275100'}, '위키드': {'영화제목: 위키드, 개봉일: 2024-11-20, 누적관객: 2195165, 누적매출: 21677201940'}, '시빌 워: 분열의 시대': {'영화제목: 시빌 워: 분열의 시대, 개봉일: 2024-12-31, 누적관객: 80373, 누적매출: 836845230'}, '동화지만 청불입니다': {'영화제목: 동화지만 청불입니다, 개봉일: 2025-01-08, 누적관객: 157616, 누적매출: 1465916720'}, '서브스턴스': {'영화제목: 서브스턴스, 개봉일: 2024-12-11, 누적관객: 302870, 누적매출: 2954609400'

**출력예시**
```
{'하얼빈': {'영화제목': '하얼빈', '개봉일': '2024-12-24', '누적관객': '4642215', '누적매출': '44407362460'}, '소방관': {'영화제목': '소방관', '개봉일': '2024-12-04', '누적관객': '3840551', '누적매출': '36145572270'}, '보고타: 마지막 기회의 땅': {'영화제목': '보고타: 마지막 기회의 땅', '개봉일': '2024-12-31', '누적관객': '396287', '누적매출': '3669720540'}, '수퍼 소닉3': {'영화제목': '수퍼 소닉3', '개봉일': '2025-01-01', '누적관객': '322100', '누적매출': '2950620910'}, '뽀로로 극장판 바닷속 대모험': {'영화제목': '뽀로로 극장판 바닷속 대모험', '개봉일': '2025-01-01', '누적관객': '349597', '누적매출': '2996015770'}, '무파사: 라이온 킹': {'영화제목': '무파사: 라이온 킹', '개봉일': '2024-12-18', '누적관객': '833832', '누적매출': '8188072950'}, '모아나 2': {'영화제목': '모아나 2', '개봉일': '2024-11-27', '누적관객': '3522517', '누적매출': '32533317750'}, '극장판 짱구는 못말려: 우리들의 공룡일기': {'영화제목': '극장판 짱구는 못말려: 우리들의 공룡일기', '개봉일': '2024-12-18', '누적관객': '762895', '누적매출': '7177275100'}, '위키드': {'영화제목': '위키드', '개봉일': '2024-11-20', '누적관객': '2195165', '누적매출': '21677201940'}, '시빌 워: 분열의 시대': {'영화제목': '시빌 워: 분열의 시대', '개봉일': '2024-12-31', '누적관객': '80373', '누적매출': '836845230'}, '동화지만 청불입니다': {'영화제목': '동화지만 청불입니다', '개봉일': '2025-01-08', '누적관객': '157616', '누적매출': '1465916720'}, '서브스턴스': {'영화제목': '서브스턴스', '개봉일': '2024-12-11', '누적관객': '302870', '누적매출': '2954609400'}, '검은 수녀들': {'영화제목': '검은 수녀들', '개봉일': '2025-01-24', '누적관객': '606145', '누적매출': '5870106460'}, '히트맨2': {'영화제목': '히트맨2', '개봉일': '2025-01-22', '누적관객': '604875', '누적매출': '5686993120'}, '극장판 포켓몬스터 AG: 뮤와 파동의 용사 루카리오': {'영화제목': '극장판 포켓몬스터 AG: 뮤와 파동의 용사 루카리오', '개봉일': '2025-01-22', '누적관객': '64585', '누적매출': '570033160'}, '아이유 콘서트 : 더 위닝': {'영화제목': '아이유 콘서트 : 더 위닝', '개봉일': '2025-01-24', '누적관객': '28061', '누적매출': '778067000'}, '귀신경찰': {'영화제목': '귀신경찰', '개봉일': '2025-01-24', '누적관객': '21949', '누적매출': '191035980'}}
```

## 일별 박스오피스 영화의 상세정보

- **일별 박스오피스 api**와 **영화 상세정보 api**를 사용합니다.
- 입력받은 날짜의 일별 박스오피스 TOP 10을 조회합니다.
- 각 영화의 상세 정보를 추가로 조회하여 다음 정보를 출력합니다:
    - 순위
    - 영화제목
    - 감독
    - 주연배우 (최대 3명)

In [14]:
kdaily_url = url_maker.daily_boxoffice_url('20250201')
kmovie_daily = requests.get(kdaily_url)
kdaily = kmovie_daily.json()
print(kdaily)

{'boxOfficeResult': {'boxofficeType': '일별 박스오피스', 'showRange': '20250201~20250201', 'dailyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '1663433100', 'salesShare': '39.5', 'salesInten': '525167660', 'salesChange': '46.1', 'salesAcc': '17240257840', 'audiCnt': '177129', 'audiInten': '40686', 'audiChange': '29.8', 'audiAcc': '1831557', 'scrnCnt': '1495', 'showCnt': '6165'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20247450', 'movieNm': '검은 수녀들', 'openDt': '2025-01-24', 'salesAmt': '934872220', 'salesShare': '22.2', 'salesInten': '247202440', 'salesChange': '35.9', 'salesAcc': '13206216740', 'audiCnt': '96043', 'audiInten': '14734', 'audiChange': '18.1', 'audiAcc': '1363840', 'scrnCnt': '1192', 'showCnt': '4387'}, {'rnum': '3', 'rank': '3', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20223819', 'movieNm': '말할 수 없는 비밀', 'ope

In [167]:
def get_movie_details(target_date):
    kdaily_url = url_maker.daily_boxoffice_url('20250201')
    kmovie_daily = requests.get(kdaily_url)
    kdaily = kmovie_daily.json()
    kd = kdaily['boxOfficeResult']['dailyBoxOfficeList']

    cd = []
    ld = lambda x: '감독 없음' if len(movieinfo['directors']) == 0 else movieinfo['directors'][0].get('peopleNm')
    ld2 = lambda y: (movieinfo['actors'][k].get('peopleNm') for k in range(3)) if len(y) > 3 else (movieinfo['actors'][k].get('peopleNm') for k in range(len(movieinfo['actors'])))
    
    for i in range(10):
        cd.append(kd[i]['movieCd'])

        for j in cd:
            info_url = url_maker.movie_info_url(j)
            movie_info = requests.get(info_url)
            movie_detail = movie_info.json()
            movieinfo = movie_detail['movieInfoResult']['movieInfo']
        
        print(f'{kd[i]['rank']}위')
        print(f'{movieinfo['movieNm']} ({movieinfo['prdtYear']})')
        print(f'감독: {ld(movieinfo['directors'])}')     
        print(f'주연: {', '.join(ld2(movieinfo['actors']))}')
        print('-----')
    

In [168]:
get_movie_details("20250201")  # YYYYMMDD 형식으로 날짜 입력

1위
히트맨2 (2023)
감독: 최원섭
주연: 권상우, 정준호, 이이경
-----
2위
검은 수녀들 (2024)
감독: 권혁재
주연: 송혜교, 전여빈, 이진욱
-----
3위
말할 수 없는 비밀 (2021)
감독: 서유민
주연: 도경수, 원진아, 신예은
-----
4위
하얼빈 (2024)
감독: 우민호
주연: 현빈, 박정민, 조우진
-----
5위
서브스턴스 (2024)
감독: 코랄리 파르쟈
주연: 데미 무어, 마가렛 퀄리, 데니스 퀘이드
-----
6위
극장판 포켓몬스터 AG: 뮤와 파동의 용사 루카리오 (2005)
감독: 유야마 쿠니히코
주연: 마츠모토 리카, 오오타니 이쿠에, 우에다 유지
-----
7위
뽀로로 극장판 바닷속 대모험 (2024)
감독: 윤제완
주연: 이선, 이미자, 함수정
-----
8위
바다 탐험대 옥토넛 어보브 앤 비욘드 : 극지방 대작전 (2024)
감독: 감독 없음
주연: 하성용, 정재헌, 엄상현
-----
9위
극장판 짱구는 못말려: 우리들의 공룡일기 (2024)
감독: 사사키 시노부
주연: 박영남, 강희선, 김환진
-----
10위
아이유 콘서트 : 더 위닝 (2024)
감독: 이예지
주연: 이지은
-----


In [ ]:
print(f'감독: {movieinfo['directors'][0].get('peopleNm')}')

**출력예시**

```
1위
히트맨2
감독: 최원섭
주연: 권상우, 정준호, 이이경
----------------------------------------

2위
검은 수녀들
감독: 권혁재
주연: 송혜교, 전여빈, 이진욱
----------------------------------------

3위
말할 수 없는 비밀
감독: 서유민
주연: 도경수, 원진아, 신예은
----------------------------------------
...
```

## 배우검색

- **영화인목록 api**, **영화인 상세정보 api**, **영화 상세정보 api**를 사용합니다.
- 배우 이름을 입력받아 해당 배우의 정보를 검색합니다.
- 여러 명의 동명 배우가 있는 경우, 필모그래피가 가장 많은 배우를 선택합니다.
- 선택된 배우의 출연작 중 '배우'로 참여한 작품 5개의 정보를 출력합니다:
    - 영화 제목
    - 개봉일
    - 상영시간
    - 감독

In [175]:
people_url = url_maker.people_list_url(peopleNm='박정민')
people_list = requests.get(people_url)
pl = people_list.json()
print(pl)

pdetail_url = url_maker.people_info_url('20291200')
print(pdetail_url)

info_url = url_maker.movie_info_url('19950084')
movie_info = requests.get(info_url)
movie_detail = movie_info.json()


{'peopleListResult': {'totCnt': 35, 'peopleList': [{'peopleCd': '20291200', 'peopleNm': '박정민', 'peopleNmEn': '', 'repRoleNm': '미술팀', 'filmoNames': '은빛살구|대도시의 사랑법|보호자|한산 리덕스|한산: 용의 출현|마녀(魔女) Part2. The Other One|액션히어로|침입자|목격자|메소드'}, {'peopleCd': '20134442', 'peopleNm': '박정민', 'peopleNmEn': '', 'repRoleNm': 'VFX 아티스트', 'filmoNames': '싱글 인 서울|4분 44초|비공식작전|범죄도시3|앵커|한산 리덕스|한산: 용의 출현|킹메이커|소울메이트|리멤버|비와 당신의 이야기|해치지않아|백두산|속물들|신의 한 수: 귀수편|퍼펙트맨|배심원들|돈|극한직업|명당|공작|흥부: 글로 세상을 바꾼 자|감시자들|스파이|광해, 왕이 된 남자|오싹한 연애|티끌모아 로맨스|커플즈|완득이|위험한 상견례|로맨틱 헤븐|나는 아빠다'}, {'peopleCd': '20336303', 'peopleNm': '박정민', 'peopleNmEn': '', 'repRoleNm': '배급진행', 'filmoNames': '베테랑2|탈출: 프로젝트 사일런스|외계+인 2부|더 문|천박사 퇴마 연구소: 설경의 비밀|헤어질 결심|브로커|카운트|방법: 재차의|발신제한|백두산|클로젯|기묘한 가족'}, {'peopleCd': '20183188', 'peopleNm': '박정민', 'peopleNmEn': '', 'repRoleNm': '촬영팀', 'filmoNames': "탈출: 프로젝트 사일런스|서울의 봄|천박사 퇴마 연구소: 설경의 비밀|늑대사냥|기생충|버닝|부라더|범죄도시|중독노래방|불한당: 나쁜 놈들의 세상|스플릿|국가대표 2|부산행|곡성|로봇, 소리|그놈이다|란제리살인사건|악의 연대기|약장수|철의 꿈|해무(海霧)|깡철이|연애의 온도|박수건달|내가 고백을 하면

In [220]:
def analyze_actor_movies(actor_name):
    people_url = url_maker.people_list_url(peopleNm=actor_name)
    people_list = requests.get(people_url)
    pl = people_list.json()
    p = pl['peopleListResult']['peopleList']

    pdic = {}
    
    for i in range(len(p)):
        if p[i]['repRoleNm'] == '배우':
            pdic = p[i]

    code = pdic['peopleCd']
        

    pdetail_url = url_maker.people_info_url(code)
    people_info = requests.get(pdetail_url)
    pi = people_info.json()

    pp = pi['peopleInfoResult']['peopleInfo']['filmos']
    
    print(f'배우 {actor_name}의 최근 출연작 5개')
    
    for j in range(5):
        pp[j]['movieNm']
        mcode = pp[j]['movieCd']
        m = url_maker.movie_info_url(mcode)
        mm = requests.get(m).json()

        movie = mm['movieInfoResult']['movieInfo']
 
    
        print(f'제목: {movie['movieNm']}')
        print(f'개봉일: {movie['openDt']}')
        print(f'상영시간: {movie['showTm']}분')
        print(f'감독: {movie['directors'][0]['peopleNm']}') 
        print('-----')

    

In [221]:
analyze_actor_movies("박정민")  # 원하는 배우 이름으로 변경 가능

배우 박정민의 최근 출연작 5개
제목: 하얼빈
개봉일: 20241224
상영시간: 113분
감독: 우민호
-----
제목: 얼굴
개봉일: 
상영시간: 분
감독: 연상호
-----
제목: 전, 란
개봉일: 
상영시간: 126분
감독: 김상만
-----
제목: 휴민트
개봉일: 
상영시간: 분
감독: 류승완
-----
제목: 밀수
개봉일: 20230726
상영시간: 129분
감독: 류승완
-----


**출력예시**

```
배우 '박정민'의 최근 출연작 5개

제목: 하얼빈
개봉일: 20241224
상영시간: 113분
감독: 우민호

제목: 얼굴
개봉일: 
상영시간: 분
감독: 연상호

제목: 전, 란
개봉일: 
상영시간: 126분
감독: 김상만

제목: 휴민트
개봉일: 
상영시간: 분
감독: 류승완

제목: 밀수
개봉일: 20230726
상영시간: 129분
감독: 류승완
```